#!/usr/bin/env python3
"""Generate port/src/symbols.h from the decompilation.

Data globals become DS_<ADDR8> = linear address (the Ghidra identifier encodes
the address; the 0x80000 data-object base is already included). Both the DAT_<a>
and PTR_<kind>_<a> identifier forms contribute: a pointer table (e.g.
PTR_FUN_000a8644) is itself a data-object symbol. Functions become FN_<NAME> =
linear address, from prage.functions.csv.

Only addresses inside an LE object are emitted. Ghidra also mints identifiers
from the 16-bit real-mode DOS stub it decompiled as 32-bit; those addresses fall
outside every object and are listed in the generated header instead.
usage: gen_symbols.py port/decomp port/src/symbols.h
"""
import csv
import re
import sys

# PRAGE.EXE LE object table (tools/le_info.py; mirror of port/src/mem.h):
#   object 0 code  base 0x10000, size 0x63B15 -> [0x10000, 0x73B15)
#   object 1 data  base 0x80000, size 0x8B0D0 -> [0x80000, 0x10B0D0)
CODE_LO, CODE_HI = 0x10000, 0x73B15
DATA_LO, DATA_HI = 0x80000, 0x10B0D0

# No word boundary: Ghidra also emits _DAT_<addr> and _PTR_<kind>_<addr> for a
# symbol overlapping smaller ones at the same address; the inner form must match.
# The kind segment holds underscores for multi-segment names such as
# PTR_s_ASSHOLE_000804ab_1_0009af40 (string address + index + storage address);
# matching it greedily keeps only the trailing 8-hex-digit storage address.
GLOB_RE = re.compile(r"(?:DAT|PTR_[A-Za-z0-9_]+)_([0-9a-fA-F]{8})")


def main(decomp_dir, out_path):
    funcs = {}
    dropped_funcs = []
    with open(f"{decomp_dir}/prage.functions.csv", newline="") as f:
        for row in csv.DictReader(f):
            name = row["name"]
            if name.startswith("FUN_.image__"):
                continue
            addr = int(row["entry"], 16)
            if not (CODE_LO <= addr < CODE_HI):
                dropped_funcs.append(addr)
                continue
            funcs[addr] = name

    src = open(f"{decomp_dir}/prage.c", encoding="latin1").read()
    found = {int(m, 16) for m in GLOB_RE.findall(src)}
    globals_ = sorted(a for a in found
                      if CODE_LO <= a < CODE_HI or DATA_LO <= a < DATA_HI)
    dropped_globals = sorted(found - set(globals_))

    with open(out_path, "w") as o:
        o.write("/* GENERATED by tools/gen_symbols.py — do not edit. */\n")
        o.write("#ifndef PR_SYMBOLS_H\n#define PR_SYMBOLS_H\n\n")
        o.write("/* Data globals: linear addresses inside the LE objects, base 0x80000\n")
        o.write(" * already included. Ghidra identifiers outside the code object\n")
        o.write(" * [0x10000,0x73B15) and data object [0x80000,0x10B0D0) are 16-bit\n")
        o.write(" * real-mode DOS-stub artifacts and are omitted (listed at the end). */\n")
        for addr in globals_:
            o.write(f"#define DS_{addr:08X} 0x{addr:08X}u\n")
        o.write("\n/* Functions: linear addresses (code object base 0x10000). */\n")
        for addr in sorted(funcs):
            name = funcs[addr]
            suffix = name[4:] if name.startswith("FUN_") else name
            o.write(f"#define FN_{suffix.upper()} 0x{addr:08X}u\n")
        o.write("\n/* Omitted out-of-object identifiers (real-mode DOS stub; no LE\n")
        o.write(" * object covers these linear addresses, so they cannot resolve\n")
        o.write(" * through mem[]): */\n")
        for addr in dropped_globals:
            o.write(f"/*   DS_ {addr:08X} */\n")
        for addr in sorted(dropped_funcs):
            o.write(f"/*   FN_ {addr:08X} */\n")
        o.write("\n#endif /* PR_SYMBOLS_H */\n")
    print(f"{len(globals_)} globals, {len(funcs)} functions -> {out_path}")
    print(f"  dropped {len(dropped_globals)} globals, {len(dropped_funcs)} "
          "functions outside the LE objects")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
