#!/usr/bin/env python3
"""Generate port/src/symbols.h from the decompilation.

Data globals become DS_<ADDR8> = linear address (the Ghidra identifier encodes
the address; the 0x80000 data-object base is already included).
Functions become FN_<NAME> = linear address, from prage.functions.csv.
usage: gen_symbols.py port/decomp port/src/symbols.h
"""
import csv
import re
import sys


def main(decomp_dir, out_path):
    funcs = {}
    with open(f"{decomp_dir}/prage.functions.csv", newline="") as f:
        for row in csv.DictReader(f):
            name = row["name"]
            if name.startswith("FUN_.image__"):
                continue
            funcs[int(row["entry"], 16)] = name

    src = open(f"{decomp_dir}/prage.c", encoding="latin1").read()
    globals_ = sorted({int(m, 16)
                       for m in re.findall(r"DAT_([0-9a-fA-F]{8})", src)})

    with open(out_path, "w") as o:
        o.write("/* GENERATED by tools/gen_symbols.py — do not edit. */\n")
        o.write("#ifndef PR_SYMBOLS_H\n#define PR_SYMBOLS_H\n\n")
        o.write("/* Data globals: linear addresses, base 0x80000 already included. */\n")
        for addr in globals_:
            o.write(f"#define DS_{addr:08X} 0x{addr:08X}u\n")
        o.write("\n/* Functions: linear addresses (code object base 0x10000). */\n")
        for addr in sorted(funcs):
            name = funcs[addr]
            suffix = name[4:] if name.startswith("FUN_") else name
            o.write(f"#define FN_{suffix.upper()} 0x{addr:08X}u\n")
        o.write("\n#endif /* PR_SYMBOLS_H */\n")
    print(f"{len(globals_)} globals, {len(funcs)} functions -> {out_path}")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
